In [1]:
import torch
import numpy as np

In [2]:
sd = torch.load('r50_1x_sk0.pth')

In [3]:
simclr = sd['resnet']

In [6]:
sd = torch.load('../ssl/saved_models/pytorch_moco/model_best.pth.tar', map_location='cpu')

In [12]:
moco = sd['state_dict']

In [38]:
print(len(simclr.keys()), len(moco.keys()))

320 320


In [17]:
from collections import OrderedDict

simclr_new_dict = OrderedDict()


translate = {'net.0':'layer1.0', 'net.1':'layer1.1', 'net.2':'layer2.0', 'net.3':'layer3.0', 'net.4':'layer4.0'}

for name, val in simclr.items():
    if name[:4] == 'net.':
        simclr_new_dict[translate[name[:5]]+name[5:]] = val
    else:
        simclr_new_dict[name] = val

In [19]:
torch.save(simclr_new_dict, 'adjusted_simclr_r50.pth')

In [4]:
adjusted = torch.load('adjusted_simclr_r50.pth', map_location='cpu')

In [6]:
for idx, tup in enumerate(simclr.items()):
    print(tup[1] == list(adjusted.items())[idx][1])

tensor([[[[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True]],

         [[True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          ...,
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ..., True, True, True],
          [True, True, True,  ...

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, Tr

tensor([[[[True]],

         [[True]],

         [[True]],

         ...,

         [[True]],

         [[True]],

         [[True]]],


        [[[True]],

         [[True]],

         [[True]],

         ...,

         [[True]],

         [[True]],

         [[True]]],


        [[[True]],

         [[True]],

         [[True]],

         ...,

         [[True]],

         [[True]],

         [[True]]],


        ...,


        [[[True]],

         [[True]],

         [[True]],

         ...,

         [[True]],

         [[True]],

         [[True]]],


        [[[True]],

         [[True]],

         [[True]],

         ...,

         [[True]],

         [[True]],

         [[True]]],


        [[[True]],

         [[True]],

         [[True]],

         ...,

         [[True]],

         [[True]],

         [[True]]]])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
    

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, Tr

In [42]:
for idx, (key_name,tensor) in enumerate(simclr.items()):
    #print()
#     if list(moco.items())[idx][1].shape != tensor.shape:
#         print(idx)
#     else:
#         print(True)
    print(list(moco.items())[idx][0], ' || ', key_name, ' || ', list(moco.items())[idx][1].shape==tensor.shape)

module.conv1.weight  ||  net.0.0.weight  ||  True
module.bn1.weight  ||  net.0.1.0.weight  ||  True
module.bn1.bias  ||  net.0.1.0.bias  ||  True
module.bn1.running_mean  ||  net.0.1.0.running_mean  ||  True
module.bn1.running_var  ||  net.0.1.0.running_var  ||  True
module.bn1.num_batches_tracked  ||  net.0.1.0.num_batches_tracked  ||  True
module.layer1.0.conv1.weight  ||  net.1.blocks.0.projection.shortcut.weight  ||  False
module.layer1.0.bn1.weight  ||  net.1.blocks.0.projection.bn.0.weight  ||  False
module.layer1.0.bn1.bias  ||  net.1.blocks.0.projection.bn.0.bias  ||  False
module.layer1.0.bn1.running_mean  ||  net.1.blocks.0.projection.bn.0.running_mean  ||  False
module.layer1.0.bn1.running_var  ||  net.1.blocks.0.projection.bn.0.running_var  ||  False
module.layer1.0.bn1.num_batches_tracked  ||  net.1.blocks.0.projection.bn.0.num_batches_tracked  ||  True
module.layer1.0.conv2.weight  ||  net.1.blocks.0.net.0.weight  ||  False
module.layer1.0.bn2.weight  ||  net.1.blocks.0.n